
const rooms=[
    {name:'Single Room', img:'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/minimal-bedroom-small-spaces-1551546274.jpg', price:124, featured:true, persons:'1 Person', id:1, description:'The Single Room is a one-room suite with queen-size bed and comfortable seating area. It is located downstairs with an outside entrance and is wheelchair assessable. It has a 39-inch flat screen TV and electric fireplace. The butler kitchen (refrigerator, microwave, Keurig coffee brewer are provided). Coffee, tea and amenities are supplied. The large bathroom has a 60-inch shower (no tub). The entire suite is designed in a fashion to allow mobility impaired accessibility.', title:'Enjoy the sound of mother nature'},
    {name:'Glass Apartment', img:'https://mydecorative.com/wp-content/uploads/2020/06/chic-black-and-white-apartment-design.jpg', price:269, persons:'3-5 Persons', id:2, description:'Our Deluxe Glass Apartment also provides views over landscaped gardens. It has a seating area, digital safe, minibar and luxurious duck down bedding. This room can be configured with either 2 single beds or zip and linked to provide a large double bed.', title:'Suround yourself with reflections'},
    {name:'Black Swan', img:'https://cdn.homedsgn.com/wp-content/uploads/2014/04/Residence-Song-03.jpg', price:344, featured:true, persons:'2 Persons', id:3, description:'Beauty is in the details that will be captured in the memories of your holiday in Venice.One unforgettable feature of the Superior Experience is the bamboo parquet that create a warm and cosy environment, enriched by art objects expertly distributed throughout each room.', title:'Dive in the black lake'},
    {name:'White Love Nest', img:'https://qtxasset.com/hotelmanagement/1551371746/Hotel-Ottilia-Suite_bedroom.jpg?CTPVy_Pq8BRc23xoRoFDidu8SDjVCBBO',price:374, persons:'2 Persons', id:4, description:'Our White Love Nest provides views over landscaped gardens. It has a seating area, ample storage, digital safe, minibar and luxurious duck down bedding.The suites are self-catering (no daily maid service) with enough linens for two days. If your stay is longer than 2 nights, someone will pick up dirty towels and freshen the room on the 3rd day.', title:'Bridsong for two swans'},
    {name:'Space Swan', img:'https://sivak-partners.com/wp-content/uploads/2020/05/1-2-1.jpg',price:458, featured:true, persons:'3-5 Persons', id:5, description:'This is the perfect suite to accommodate a family! It offers two separate bedrooms, with a double bed and bunk bed respectively and a bathroom with a walk-in shower.The spacious living room also features a dining table creating a perfect area for enjoying private meals and family activities with amazing view to the Pirin Mountain and forest.', title:'The elegance of space'},
    {name:'White Room', img:'https://33decor.com/wp-content/uploads/2019/03/33-Ideas-For-Small-Apartment-Bedroom-5.jpg',price:135, persons:'1 Person', id:6, description:'Nicely appointed suites with welcoming, residential ambience; offering modern day comfort, enjoying views of the hotel surrounding areas and partial views of the city of Bansko. The master bedroom features a private balcony and an en-suite bathroom with wash-hand basin and shower cabin; while the second bathroom can be accessible from both bedrooms and features a deep soak bathtub. The guests will appreciate the relaxation of the two bedrooms, separated from the living room for added comfort and convenience.', title:'Dream in white colors'},
]


export default rooms